main.py
from datetime import timedelta
from flask import Flask
from flask_socketio import SocketIO
import socket

# local imports
from routes.routes_main import main
from routes.routes_lobby import lobby
from routes.routes_flip7 import flip7

from socketio_events.init import init_socket_events
# from socketEvents import socketEventsInit, currentPlayers


app = Flask(__name__, static_url_path='/static')

app.secret_key = b'aipsterKeyWuh'
app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(days=1)


socketio = SocketIO(app, ping_interval=60, ping_timeout=600)


app.register_blueprint(main, url_prefix='/')
app.register_blueprint(lobby, url_prefix='/')
app.register_blueprint(flip7, url_prefix='/')


connectedIpAddresses = {}


def getLocalIp():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(('8.8.8.8', 80))
        return s.getsockname()[0]
    finally:
        s.close()


if __name__ == '__main__':
    host = '0.0.0.0'
    port = 5000
    localIp = getLocalIp()

    print("========== SERVER-INFO ==========")
    print("Flask-QuizGame Server gestartet")
    print(f"Lokale Adresse:    http://localhost:{port}")
    print("=================================\n")

    # Init for all socketEvents
    init_socket_events(socketio, connectedIpAddresses)

    socketio.run(app, host=host, port=port, debug=True)

routes/routes_main.py
from flask import flash, redirect, render_template, session, url_for, Blueprint
from flask import render_template, request

from manager.PlayerManager import currentPlayers

main = Blueprint('main', __name__,
                       template_folder='../templates/main',
                       static_folder='/static')

@main.route('/')
def index():
    session.clear()
    print("[ROUTE] Aufgerufen: / (index)")

    return render_template('index.html')


@main.route('/register', methods=['GET', 'POST'])
def register():
    print("[ROUTE] Aufgerufen: / (register)")
    

    if request.method == 'POST':
        username = (request.form.get('name') or '').strip()

        if any(u.lower() == username.lower() for u in currentPlayers):
            flash('Username already taken. Please choose another.', 'error')
            # Either re-render the form:
            return render_template('register.html', username=username), 409
        
        # todo: check if user is already registered so you can not register 2 times with different usernames

        session["user_Id"] = username

        lowerCaseName = username.lower()
        ipAddress = request.remote_addr

        if lowerCaseName in currentPlayers and currentPlayers[lowerCaseName]["status"] == "disconnected":
            currentPlayers[lowerCaseName]["status"] = "connected"
            print(f"Spieler RECONNECTED: {username} (IP: {ipAddress})")
            return

        playerData = {
            'username': username,
            'sid': "",
            'ip': ipAddress,
            'status': "connected"
        }

        currentPlayers[lowerCaseName] = playerData

        print(currentPlayers)

        return redirect(url_for('lobby.main_lobby',))
    
    return render_template('register.html')

templates/main/index.html
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pia und Pascals Party-Plattform</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main/index.css') }}">
</head>
</head>

<body>
  <div class="header">Pia und Pascals Party-Plattform</div>

<div class="center-buttons">
  <a href="{{ url_for('main.register') }}">
    <button class="big-button">Games</button>
  </a>
  <button class="big-button">Tools</button>
</div>

</body>
</html>

templates/main/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Quizspiel - Join</title>
    <!-- <script src="https://cdn.socket.io/4.7.2/socket.io.min.js"></script>
    

    <script type="module" src="{{ url_for('static', filename='js/register.js') }}"></script>-->
       <link rel="stylesheet" href="{{ url_for('static', filename='css/main/register.css') }}">
</head>
<body>

    <!--{% with msgs = get_flashed_messages(with_categories=True) %}
    {% if msgs %}
        <ul class="flashes">
        {% for cat, msg in msgs %}
            <li class="flash {{ cat }}">{{ msg }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    {% endwith %}-->

  <div id="join" class="form-container">
    <form method="post">
      <input name="name" class="name-input" placeholder="Name eingeben">
      <button type="submit" class="big-button">Registrieren</button>
    </form>
  </div>
</body>
</html>