routes/routes_lobby.py
from flask import redirect, render_template, Blueprint, request, session, url_for
from manager.LobbyManager import lobbyStorage


lobby = Blueprint('lobby', __name__,
                        template_folder='../templates/lobbys',
                        static_folder='static')
                    

# --- Main lobby route ---
@lobby.route('/lobby')
def main_lobby():
    print("[ROUTE] Aufgerufen: / (lobby)")
    print("user_Id: ", session["user_Id"])
    if 'user_Id' not in session:
        # not registered so return to /register
        return redirect(url_for('main.register'))

    return render_template('main_lobby.html')


# --- Flip7 lobby routes ---
@lobby.route('/lobby/flip7')
def flip7_main_lobby():
    print("[ROUTE] Aufgerufen: /lobby/flip7")

    # shows all existing lobbys
    openFlip7Lobbies = lobbyStorage.listOpen()

    return render_template('flip7_main_lobby.html', openFlip7Lobbies = openFlip7Lobbies)


@lobby.route('/lobby/flip7/create', methods=['GET', 'POST'])
def flip7_create_lobby():
    print("[ROUTE] Aufgerufen: /lobby/flip7/create")
    
    if request.method == 'POST':
        name = (request.form.get('name') or 'Neue Lobby').strip()
        
        lobby = lobbyStorage.create(name=name, lobbyType='flip7', hostId=session["user_Id"])

        return redirect(url_for('lobby.flip7_game_lobby', id=lobby.id))
    
    return render_template('flip7_create_lobby.html')


@lobby.route('/lobby/flip7/<string:id>', methods=['GET', 'POST'])
def flip7_game_lobby(id):
    print("[ROUTE] Aufgerufen: /lobby/flip7/id")

    flip7Lobby = lobbyStorage.get(id)

    print("lobbyId:", flip7Lobby.id)
    
    return render_template('flip7_game_lobby.html', flip7LobbyId=id, lobby=flip7Lobby, session = session)

templates/lobbys/flip7_create_lobby.html
<head>
    <script src="https://cdn.socket.io/4.7.2/socket.io.min.js"></script>
    <script type="module" src="{{ url_for('lobby.static', filename='js/lobby.js') }}" defer></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/lobby/flip7CreateLobby.css') }}">
</head>
<div class="form-wrapper">
  <img src="{{ url_for('static', filename='assets/images/flip7/7FlipLogoWordLobby.png') }}" alt="Logo" class="header-logo">

  <form method="post" class="form-container">
    <label for="name">Lobbyname:</label>
    <input id="name" name="name" placeholder="Lobbyname">

    <label for="max_players">Max. Spieler:</label>
    <input id="max_players" name="max_players" type="number" min="2" max="7" value="7">

    <button type="submit">create</button>
  </form>
</div>

templates/lobbys/flip7_game_lobby.html
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lobby</title>
    <script src="https://cdn.socket.io/4.7.2/socket.io.min.js"></script>
    <script type="module" src="{{ url_for('lobby.static', filename='js/flip7Lobby.js') }}" defer></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/lobby/flip7GameLobby.css') }}">
</head>
<body>

    <script>
        window.socket = io();
        var lobbyId = "{{ flip7LobbyId }}";
        window.socket.emit('join_room', { lobbyId: lobbyId });

        window.socket.on('redirect', ({ url }) => {
            window.location.href = url;
        });

        function startGame(){
            var lobbyId = "{{ flip7LobbyId }}";
            window.socket.emit('start_game', { lobbyId: lobbyId });
        }
    </script>



<div class="header-container">
      <img src="{{ url_for('static', filename='assets/images/flip7/7FlipLogoWordLobby.png') }}" alt="Logo" class="header-logo">

    </div><div class="main-container">
    <div class="content-container">
        <h2>Mitspieler</h2>
        <ul class="players-list">
            {% for member in lobby.members %}
                <li class="player-item">{{ member.name }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="hostButton-container">
        {% if lobby.host_Id == session["user_Id"] %}
            <div class="start-container">
                <button type="button" class="ready-button" onclick="startGame()">Start Game</button>
            </div>
        {% endif %}
    </div>
</div>

        <div class="footer-container">
            <a href="{{ url_for('lobby.flip7_main_lobby') }}">
                <button class="back-button">Zurück</button>
            </a>
        </div>
</body>
</html>


  <!--  <div class="dialog">
        Inhalt mittig
        <div class="dialog-content">
            <img src="{{ url_for('lobby.static', filename='img/logo.png') }}" alt="Logo" class="header-logo">

            <h1 class="header">flipSeven GameLobby</h1>

            <div class="players-container">

            </div>

            {% if lobby.hostId == session["uid"] %}
            <div class="start-container">
                <button type="button" class="ready-button" onclick="startGame()">Start Game</button>
            </div>
            {% endif %}
        </div>

         Zurück Button unten links
        <div class="footer-container">
            <a href="{{ url_for('lobby.flip7_main_lobby') }}">
                <button class="back-button">Zurück</button>
            </a>
        </div>
    </div>-->

templates/lobbys/flip7_main_lobby.html
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lobby</title>
    <script src="https://cdn.socket.io/4.7.2/socket.io.min.js"></script>
    <script type="module" src="{{ url_for('lobby.static', filename='js/lobby/flip7Lobby.js') }}" defer></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/lobby/flip7GameLobby.css') }}">
    <script>
        window.socket = io(); // global

        window.socket.on('connect', () => console.log('connected as', window.socket.id));

        window.socket.on('redirect', ({ url }) => {
            console.log('redirect to', url);
            window.location.href = url;
        });

        function joinLobby(lobbyId) {
            window.socket.emit('join_lobby', { lobbyId });
        }
    </script>
</head>
<body>
<div class="content">
    <!-- 1. Überschrift -->
    <div class="header-container">
        <img src="{{ url_for('static', filename='assets/images/flip7/7FlipLogoWordLobby.png') }}" alt="Logo" class="header-logo">
        <!--  <h1 class="header">MainLobby</h1>  -->
    </div>

    <!-- 2. Host Button -->
    <div class="host-container">
        <a href="/lobby/flip7/create">
            <button class="ready-button">Hosten</button>
        </a>
    </div>

    <!-- 3. Liste der Lobbies -->
    <div class="lobby-container">
        {% for lobby in openFlip7Lobbies %}
        <div class="lobby-list">
            <div class="lobby-row">
                <span class="lobby-name">{{ lobby.name }}</span>
            </div>
            <div class="lobby-row">
                Host: {{ lobby.host }}
            </div>
            <div class="lobby-row"> <!-- Mitspieler einblenden -->
                {% for player in lobby.players %}
                    {{ player }}<br>
                {% endfor %}
            </div>
            <div class="lobby-row">
                <button type="button" onclick="joinLobby('{{ lobby.id }}')">Beitreten</button>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- 4. Footer / Back Button -->
    <div class="footer-container">
        <a href="{{ url_for('lobby.main_lobby') }}">
            <button class="back-button">Zurück</button>
        </a>
    </div>
    </div>

</body>
</html>

templates/lobbys/main_lobby.html
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/lobby/lobby.css') }}">
    <title>Lobby</title>
</head>
<body>

<h1>Games:</h1>

<div class="lobby">
    <div class="game">
        <a href="/lobby/quizgame"><img src="{{ url_for('lobby.static', filename='assets/images/quiz.jpg') }}" alt="Quizgame"></a>
        <div class="game-title">Quizgame</div>
    </div>
    <div class="game">
        <a href="/lobby/keywords"> <img src="{{ url_for('lobby.static', filename='assets/images/keywords.jpg') }}" alt="Keywords"></a>
        <div class="game-title">Keywords</div>
    </div>
    <div class="game">
         <a href="/lobby/flip7"> <img src="{{ url_for('lobby.static', filename='assets/images/flip7.jpg') }}"alt="Flip 7"></a>

        <div class="game-title">Flip 7</div>
    </div>
    <!-- <div class="game">
        <gameLogos src="bild4.jpg" alt="Game 4">
        <div class="game-title">Game 4</div>
    </div>
    <div class="game">
        <gameLogos src="bild5.jpg" alt="Game 5">
        <div class="game-title">Game 5</div>
    </div>
    <div class="game">
        <gameLogos src="bild6.jpg" alt="Game 6">
        <div class="game-title">Game 6</div>
    </div>
    <div class="game">
        <gameLogos src="bild7.jpg" alt="Game 7">
        <div class="game-title">Game 7</div>
    </div>
    <div class="game">
        <gameLogos src="bild8.jpg" alt="Game 8">
        <div class="game-title">Game 8</div>
    </div>-->
</div>

</body>
</html>